<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Two-way analysis of variance | A short introduction to common statistical data analysis techniques</title>
  <meta name="description" content="Chapter 7 Two-way analysis of variance | A short introduction to common statistical data analysis techniques" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Two-way analysis of variance | A short introduction to common statistical data analysis techniques" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Two-way analysis of variance | A short introduction to common statistical data analysis techniques" />
  
  
  

<meta name="author" content="Data Science Lab, University of Copenhagen" />


<meta name="date" content="2025-02-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="mixedmodels.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About this document</a></li>
<li class="chapter" data-level="1" data-path="binreg.html"><a href="binreg.html"><i class="fa fa-check"></i><b>1</b> Binary Regression</a>
<ul>
<li class="chapter" data-level="1.1" data-path="binreg.html"><a href="binreg.html#when-to-use-this-model"><i class="fa fa-check"></i><b>1.1</b> When to use this model?</a></li>
<li class="chapter" data-level="1.2" data-path="binreg.html"><a href="binreg.html#description-of-the-model"><i class="fa fa-check"></i><b>1.2</b> Description of the Model</a></li>
<li class="chapter" data-level="1.3" data-path="binreg.html"><a href="binreg.html#similarities-to-the-chi-squared-test"><i class="fa fa-check"></i><b>1.3</b> similarities to the chi-squared test</a></li>
<li class="chapter" data-level="1.4" data-path="binreg.html"><a href="binreg.html#example-1-simple-example-but-bad-model-fit"><i class="fa fa-check"></i><b>1.4</b> Example 1: Simple example but bad model fit</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="binreg.html"><a href="binreg.html#organizing-data"><i class="fa fa-check"></i><b>1.4.1</b> Organizing data</a></li>
<li class="chapter" data-level="1.4.2" data-path="binreg.html"><a href="binreg.html#fitting-model"><i class="fa fa-check"></i><b>1.4.2</b> Fitting Model</a></li>
<li class="chapter" data-level="1.4.3" data-path="binreg.html"><a href="binreg.html#model-validering-via-gof-pakken.-gerne-via-kkholst-på-github."><i class="fa fa-check"></i><b>1.4.3</b> Model validering via gof-pakken. Gerne via kkholst på github.</a></li>
<li class="chapter" data-level="1.4.4" data-path="binreg.html"><a href="binreg.html#hypothesis-test"><i class="fa fa-check"></i><b>1.4.4</b> Hypothesis test</a></li>
<li class="chapter" data-level="1.4.5" data-path="binreg.html"><a href="binreg.html#parameter-estimates-with-emmeans."><i class="fa fa-check"></i><b>1.4.5</b> Parameter estimates with emmeans.</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="binreg.html"><a href="binreg.html#example-2-multiple-variables-and-correct-model-fit"><i class="fa fa-check"></i><b>1.5</b> Example 2: Multiple variables and correct model fit</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="binreg.html"><a href="binreg.html#organizing-data-1"><i class="fa fa-check"></i><b>1.5.1</b> Organizing data</a></li>
<li class="chapter" data-level="1.5.2" data-path="binreg.html"><a href="binreg.html#fitting-model-1"><i class="fa fa-check"></i><b>1.5.2</b> Fitting Model</a></li>
<li class="chapter" data-level="1.5.3" data-path="binreg.html"><a href="binreg.html#model-validering-via-gof-pakken.-gerne-via-kkholst-på-github.-1"><i class="fa fa-check"></i><b>1.5.3</b> Model validering via gof-pakken. Gerne via kkholst på github.</a></li>
<li class="chapter" data-level="1.5.4" data-path="binreg.html"><a href="binreg.html#hypothesis-test-1"><i class="fa fa-check"></i><b>1.5.4</b> Hypothesis test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>2</b> Linear regression</a></li>
<li class="chapter" data-level="3" data-path="model-validation.html"><a href="model-validation.html"><i class="fa fa-check"></i><b>3</b> Model Validation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="model-validation.html"><a href="model-validation.html#why-and-how"><i class="fa fa-check"></i><b>3.1</b> Why and How</a></li>
<li class="chapter" data-level="3.2" data-path="model-validation.html"><a href="model-validation.html#sample-size-of-one"><i class="fa fa-check"></i><b>3.2</b> Sample size of one</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="model-validation.html"><a href="model-validation.html#data-example-1-weight-of-crabs"><i class="fa fa-check"></i><b>3.2.1</b> Data Example 1: Weight of Crabs</a></li>
<li class="chapter" data-level="3.2.2" data-path="model-validation.html"><a href="model-validation.html#data-example-2-salary-data-from-connecticut---log-transformation"><i class="fa fa-check"></i><b>3.2.2</b> Data Example 2: Salary Data from Connecticut - log transformation</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="model-validation.html"><a href="model-validation.html#sample-size-of-two"><i class="fa fa-check"></i><b>3.3</b> Sample size of two</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="model-validation.html"><a href="model-validation.html#simulated-data-example"><i class="fa fa-check"></i><b>3.3.1</b> Simulated data example</a></li>
<li class="chapter" data-level="3.3.2" data-path="model-validation.html"><a href="model-validation.html#data-example-3-lean-body-mass-and-physical-strength-for-men-and-women"><i class="fa fa-check"></i><b>3.3.2</b> Data Example 3: Lean body mass and physical strength for men and women</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="model-validation.html"><a href="model-validation.html#linear-nomral-models-regression-anova-ancova"><i class="fa fa-check"></i><b>3.4</b> Linear nomral models (regression, ANOVA, ANCOVA)</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="model-validation.html"><a href="model-validation.html#data-example-4-pillbugs-oneway-anova"><i class="fa fa-check"></i><b>3.4.1</b> Data Example 4: pillbugs (oneway ANOVA)</a></li>
<li class="chapter" data-level="3.4.2" data-path="model-validation.html"><a href="model-validation.html#data-example-5-lean-body-mass-and-physical-strength-for-men-and-women-continued"><i class="fa fa-check"></i><b>3.4.2</b> Data Example 5: Lean body mass and physical strength for men and women (continued)</a></li>
<li class="chapter" data-level="3.4.3" data-path="model-validation.html"><a href="model-validation.html#data-example-5-birthwt"><i class="fa fa-check"></i><b>3.4.3</b> Data Example 5: birthwt</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="model-validation.html"><a href="model-validation.html#miscellaneous"><i class="fa fa-check"></i><b>3.5</b> Miscellaneous</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="model-validation.html"><a href="model-validation.html#intepretation-of-results-when-transforming"><i class="fa fa-check"></i><b>3.5.1</b> Intepretation of results when transforming</a></li>
<li class="chapter" data-level="3.5.2" data-path="model-validation.html"><a href="model-validation.html#boxcox"><i class="fa fa-check"></i><b>3.5.2</b> Boxcox</a></li>
<li class="chapter" data-level="3.5.3" data-path="model-validation.html"><a href="model-validation.html#shapiro-wilk-hypothesis-test-for-normality"><i class="fa fa-check"></i><b>3.5.3</b> Shapiro Wilk hypothesis test for normality</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="onewayANOVA.html"><a href="onewayANOVA.html"><i class="fa fa-check"></i><b>4</b> One-way analysis of variance</a>
<ul>
<li class="chapter" data-level="4.1" data-path="onewayANOVA.html"><a href="onewayANOVA.html#when-to-use-this-model-1"><i class="fa fa-check"></i><b>4.1</b> When to use this model?</a></li>
<li class="chapter" data-level="4.2" data-path="onewayANOVA.html"><a href="onewayANOVA.html#organisation-of-data-and-data-import"><i class="fa fa-check"></i><b>4.2</b> Organisation of data and data import</a></li>
<li class="chapter" data-level="4.3" data-path="onewayANOVA.html"><a href="onewayANOVA.html#data-exploration"><i class="fa fa-check"></i><b>4.3</b> Data exploration</a></li>
<li class="chapter" data-level="4.4" data-path="onewayANOVA.html"><a href="onewayANOVA.html#fitting-the-model"><i class="fa fa-check"></i><b>4.4</b> Fitting the model</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="onewayANOVA.html"><a href="onewayANOVA.html#with-default-reference-group"><i class="fa fa-check"></i><b>4.4.1</b> … with default reference group</a></li>
<li class="chapter" data-level="4.4.2" data-path="onewayANOVA.html"><a href="onewayANOVA.html#without-a-reference-group"><i class="fa fa-check"></i><b>4.4.2</b> .. without a reference group</a></li>
<li class="chapter" data-level="4.4.3" data-path="onewayANOVA.html"><a href="onewayANOVA.html#with-user-defined-reference-group"><i class="fa fa-check"></i><b>4.4.3</b> … with user defined reference group</a></li>
<li class="chapter" data-level="4.4.4" data-path="onewayANOVA.html"><a href="onewayANOVA.html#digging-more-into-the-output-from-summary"><i class="fa fa-check"></i><b>4.4.4</b> Digging more into the output from <code>summary()</code></a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="onewayANOVA.html"><a href="onewayANOVA.html#validating-the-model"><i class="fa fa-check"></i><b>4.5</b> Validating the model</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="onewayANOVA.html"><a href="onewayANOVA.html#why-do-i-need-to-valide-the-model"><i class="fa fa-check"></i><b>4.5.1</b> Why do I need to valide the model?</a></li>
<li class="chapter" data-level="4.5.2" data-path="onewayANOVA.html"><a href="onewayANOVA.html#how-do-i-validate-the-model-assumptions"><i class="fa fa-check"></i><b>4.5.2</b> How do I validate the model assumptions?</a></li>
<li class="chapter" data-level="4.5.3" data-path="onewayANOVA.html"><a href="onewayANOVA.html#what-to-do-if-the-model-is-not-valid"><i class="fa fa-check"></i><b>4.5.3</b> What to do if the model is not valid?</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="onewayANOVA.html"><a href="onewayANOVA.html#extracting-estimates-with-emmeans"><i class="fa fa-check"></i><b>4.6</b> Extracting estimates with <code>emmeans()</code></a></li>
<li class="chapter" data-level="4.7" data-path="onewayANOVA.html"><a href="onewayANOVA.html#reporting-the-results"><i class="fa fa-check"></i><b>4.7</b> Reporting the results</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="onewayANOVA.html"><a href="onewayANOVA.html#tables"><i class="fa fa-check"></i><b>4.7.1</b> Tables</a></li>
<li class="chapter" data-level="4.7.2" data-path="onewayANOVA.html"><a href="onewayANOVA.html#figures"><i class="fa fa-check"></i><b>4.7.2</b> Figures</a></li>
<li class="chapter" data-level="4.7.3" data-path="onewayANOVA.html"><a href="onewayANOVA.html#stat-methods-section"><i class="fa fa-check"></i><b>4.7.3</b> Stat methods section</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="onewayANOVA.html"><a href="onewayANOVA.html#alternatives-and-related-statistical-methods"><i class="fa fa-check"></i><b>4.8</b> Alternatives and related statistical methods</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="onewayANOVA.html"><a href="onewayANOVA.html#logtrans"><i class="fa fa-check"></i><b>4.8.1</b> Analysis on logtransformed scale</a></li>
<li class="chapter" data-level="4.8.2" data-path="onewayANOVA.html"><a href="onewayANOVA.html#onewaynonpar"><i class="fa fa-check"></i><b>4.8.2</b> Relation to t-tests and non-parametric testing</a></li>
<li class="chapter" data-level="4.8.3" data-path="onewayANOVA.html"><a href="onewayANOVA.html#bootstrap"><i class="fa fa-check"></i><b>4.8.3</b> When data are not normally distributed</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="poisson-regression.html"><a href="poisson-regression.html"><i class="fa fa-check"></i><b>5</b> Poisson regression</a></li>
<li class="chapter" data-level="6" data-path="mixedmodels.html"><a href="mixedmodels.html"><i class="fa fa-check"></i><b>6</b> Analysis of repeated measures</a></li>
<li class="chapter" data-level="7" data-path="twowayANOVA.html"><a href="twowayANOVA.html"><i class="fa fa-check"></i><b>7</b> Two-way analysis of variance</a>
<ul>
<li class="chapter" data-level="7.1" data-path="twowayANOVA.html"><a href="twowayANOVA.html#when-to-use-this-model-2"><i class="fa fa-check"></i><b>7.1</b> When to use this model?</a></li>
<li class="chapter" data-level="7.2" data-path="twowayANOVA.html"><a href="twowayANOVA.html#organizing-data-2"><i class="fa fa-check"></i><b>7.2</b> Organizing data</a></li>
<li class="chapter" data-level="7.3" data-path="twowayANOVA.html"><a href="twowayANOVA.html#data-exploration-1"><i class="fa fa-check"></i><b>7.3</b> Data exploration</a></li>
<li class="chapter" data-level="7.4" data-path="twowayANOVA.html"><a href="twowayANOVA.html#fitting-model-2"><i class="fa fa-check"></i><b>7.4</b> Fitting model</a></li>
<li class="chapter" data-level="7.5" data-path="twowayANOVA.html"><a href="twowayANOVA.html#validating-the-model-1"><i class="fa fa-check"></i><b>7.5</b> Validating the model</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="twowayANOVA.html"><a href="twowayANOVA.html#why-do-i-need-to-valide-the-model-1"><i class="fa fa-check"></i><b>7.5.1</b> Why do I need to valide the model?</a></li>
<li class="chapter" data-level="7.5.2" data-path="twowayANOVA.html"><a href="twowayANOVA.html#how-do-i-validate-the-model-assumptions-1"><i class="fa fa-check"></i><b>7.5.2</b> How do I validate the model assumptions?</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="twowayANOVA.html"><a href="twowayANOVA.html#hypothesis-test-2"><i class="fa fa-check"></i><b>7.6</b> Hypothesis test</a></li>
<li class="chapter" data-level="7.7" data-path="twowayANOVA.html"><a href="twowayANOVA.html#extracting-estimates-with-emmeans-1"><i class="fa fa-check"></i><b>7.7</b> Extracting estimates with <code>emmeans()</code></a></li>
<li class="chapter" data-level="7.8" data-path="twowayANOVA.html"><a href="twowayANOVA.html#writing-articlereport"><i class="fa fa-check"></i><b>7.8</b> Writing article/report</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="twowayANOVA.html"><a href="twowayANOVA.html#how-to-write-method-section"><i class="fa fa-check"></i><b>7.8.1</b> How to write method section</a></li>
<li class="chapter" data-level="7.8.2" data-path="twowayANOVA.html"><a href="twowayANOVA.html#how-to-write-results-section"><i class="fa fa-check"></i><b>7.8.2</b> How to write results section</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="twowayANOVA.html"><a href="twowayANOVA.html#miscellaneous-1"><i class="fa fa-check"></i><b>7.9</b> Miscellaneous</a>
<ul>
<li class="chapter" data-level="7.9.1" data-path="twowayANOVA.html"><a href="twowayANOVA.html#why-to-not-use-anova-tables"><i class="fa fa-check"></i><b>7.9.1</b> Why to not use ANOVA tables</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A short introduction to common statistical data analysis techniques</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="twowayANOVA" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Two-way analysis of variance<a href="twowayANOVA.html#twowayANOVA" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="twowayANOVA.html#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb126-2"><a href="twowayANOVA.html#cb126-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb126-3"><a href="twowayANOVA.html#cb126-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vtable)</span></code></pre></div>
<div id="when-to-use-this-model-2" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> When to use this model?<a href="twowayANOVA.html#when-to-use-this-model-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A two-way ANOVA is used to estimate how the mean of a quantitative variable changes according to the levels of two categorical variables. You can use a two-way ANOVA when you want to know how two independent variables, in combination, affect a dependent variable. In this example we will use two-way anova to see if applying fertilizer to flowers at the florist or/and at the customer effects the lifespan of a rose.</p>
</div>
<div id="organizing-data-2" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Organizing data<a href="twowayANOVA.html#organizing-data-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="twowayANOVA.html#cb127-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/3_1_roser.txt&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">&quot;&quot;</span>, <span class="at">dec =</span> <span class="st">&quot;.&quot;</span>, <span class="at">colClasses =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;factor&quot;</span>,<span class="dv">4</span>),<span class="st">&quot;numeric&quot;</span>))</span>
<span id="cb127-2"><a href="twowayANOVA.html#cb127-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">as_tibble</span>(df))</span></code></pre></div>
<pre><code>## # A tibble: 24 × 5
##    gardener florist customer flor   time
##    &lt;fct&gt;    &lt;fct&gt;   &lt;fct&gt;    &lt;fct&gt; &lt;dbl&gt;
##  1 0        0       0        1      10.1
##  2 0        0       0        2       8.9
##  3 0        0       0        3      11.4
##  4 1        0       0        1      10.9
##  5 1        0       0        2       6.9
##  6 1        0       0        3      11.2
##  7 0        1       0        1       9.6
##  8 0        1       0        2       9.9
##  9 0        1       0        3      11.3
## 10 0        0       1        1      11.8
## # ℹ 14 more rows</code></pre>
<p>As this chapter is about two-way-ANOVA we will only look at two categorial variables and a responsvariable. For this data our respons variable is <code>time</code> and we choose <code>florist</code> and <code>customer</code> as our explanatory variables.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="twowayANOVA.html#cb129-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">subset</span>(df, <span class="at">select =</span> <span class="fu">c</span>(<span class="st">&quot;florist&quot;</span>,<span class="st">&quot;customer&quot;</span>,<span class="st">&quot;time&quot;</span>))</span>
<span id="cb129-2"><a href="twowayANOVA.html#cb129-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">as_tibble</span>(df))</span></code></pre></div>
<pre><code>## # A tibble: 24 × 3
##    florist customer  time
##    &lt;fct&gt;   &lt;fct&gt;    &lt;dbl&gt;
##  1 0       0         10.1
##  2 0       0          8.9
##  3 0       0         11.4
##  4 0       0         10.9
##  5 0       0          6.9
##  6 0       0         11.2
##  7 1       0          9.6
##  8 1       0          9.9
##  9 1       0         11.3
## 10 0       1         11.8
## # ℹ 14 more rows</code></pre>
<p>To understand the data better its a good idea to make a table of variables. Here are two examples: One using standard R and one using the package vtable:</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="twowayANOVA.html#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    24 obs. of  3 variables:
##  $ florist : Factor w/ 2 levels &quot;0&quot;,&quot;1&quot;: 1 1 1 1 1 1 2 2 2 1 ...
##  $ customer: Factor w/ 2 levels &quot;0&quot;,&quot;1&quot;: 1 1 1 1 1 1 1 1 1 2 ...
##  $ time    : num  10.1 8.9 11.4 10.9 6.9 11.2 9.6 9.9 11.3 11.8 ...</code></pre>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="twowayANOVA.html#cb133-1" aria-hidden="true" tabindex="-1"></a>Description <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;If fertilizer was applied at florist&quot;</span>,<span class="st">&quot;If fertilizer was applied at customer&quot;</span>,<span class="st">&quot;Days before the rose withered&quot;</span>)</span>
<span id="cb133-2"><a href="twowayANOVA.html#cb133-2" aria-hidden="true" tabindex="-1"></a>Use <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Explanatory variable&quot;</span>, <span class="st">&quot;Explanatory variable&quot;</span>, <span class="st">&quot;Response variable&quot;</span>)</span>
<span id="cb133-3"><a href="twowayANOVA.html#cb133-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">vt</span>(df, <span class="at">out =</span> <span class="st">&quot;return&quot;</span>),<span class="fu">data.frame</span>(Description,Use))</span></code></pre></div>
<pre><code>##       Name   Class           Values                           Description                  Use
## 1  florist  factor          &#39;0&#39; &#39;1&#39;  If fertilizer was applied at florist Explanatory variable
## 2 customer  factor          &#39;0&#39; &#39;1&#39; If fertilizer was applied at customer Explanatory variable
## 3     time numeric Num: 6.9 to 15.2         Days before the rose withered    Response variable</code></pre>
<p>We can see that <code>florist</code> and <code>customer</code> are both factor variables taking either 0 or 1 as values, where a 1 indicates that fertilizer has been applied and 0 indicates that fertilizer has not been applied. i.e. if <code>florist</code> has a value of 1 the fertilizer was applied at the florist. <code>time</code> is a numerical variable ranging from 6.9 to 15.2 and indicates how many days the rose survived.</p>
</div>
<div id="data-exploration-1" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Data exploration<a href="twowayANOVA.html#data-exploration-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>It is convenient to compute summarizes of the outcome divided by the factors:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="twowayANOVA.html#cb135-1" aria-hidden="true" tabindex="-1"></a>sum_customer <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb135-2"><a href="twowayANOVA.html#cb135-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(customer) <span class="sc">%&gt;%</span> </span>
<span id="cb135-3"><a href="twowayANOVA.html#cb135-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb135-4"><a href="twowayANOVA.html#cb135-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(), </span>
<span id="cb135-5"><a href="twowayANOVA.html#cb135-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_time =</span> <span class="fu">mean</span>(time), </span>
<span id="cb135-6"><a href="twowayANOVA.html#cb135-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_time =</span> <span class="fu">sd</span>(time), </span>
<span id="cb135-7"><a href="twowayANOVA.html#cb135-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_time =</span> <span class="fu">median</span>(time))</span>
<span id="cb135-8"><a href="twowayANOVA.html#cb135-8" aria-hidden="true" tabindex="-1"></a>sum_customer</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   customer     n mean_time sd_time median_time
##   &lt;fct&gt;    &lt;int&gt;     &lt;dbl&gt;   &lt;dbl&gt;       &lt;dbl&gt;
## 1 0           12      10.3    1.42        10.5
## 2 1           12      12.4    2.13        13.0</code></pre>
<p>This table suggests that applying fertilizer at the costumers has a possitive effective on the lifespan of the roses.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="twowayANOVA.html#cb137-1" aria-hidden="true" tabindex="-1"></a>sum_florist <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb137-2"><a href="twowayANOVA.html#cb137-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(florist) <span class="sc">%&gt;%</span> </span>
<span id="cb137-3"><a href="twowayANOVA.html#cb137-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb137-4"><a href="twowayANOVA.html#cb137-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(), </span>
<span id="cb137-5"><a href="twowayANOVA.html#cb137-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_time =</span> <span class="fu">mean</span>(time), </span>
<span id="cb137-6"><a href="twowayANOVA.html#cb137-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_time =</span> <span class="fu">sd</span>(time), </span>
<span id="cb137-7"><a href="twowayANOVA.html#cb137-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_time =</span> <span class="fu">median</span>(time))</span>
<span id="cb137-8"><a href="twowayANOVA.html#cb137-8" aria-hidden="true" tabindex="-1"></a>sum_florist</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   florist     n mean_time sd_time median_time
##   &lt;fct&gt;   &lt;int&gt;     &lt;dbl&gt;   &lt;dbl&gt;       &lt;dbl&gt;
## 1 0          12      10.4    1.88        10.9
## 2 1          12      12.2    1.94        12.6</code></pre>
<p>This table suggests that applying fertilizer at the florist has a possitive effective on the lifespan of the roses.</p>
<p>We can also create a table of the combinations of the categorial variables to see if there is a possible interaction effect:</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="twowayANOVA.html#cb139-1" aria-hidden="true" tabindex="-1"></a>sum_df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb139-2"><a href="twowayANOVA.html#cb139-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(florist, customer) <span class="sc">%&gt;%</span></span>
<span id="cb139-3"><a href="twowayANOVA.html#cb139-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb139-4"><a href="twowayANOVA.html#cb139-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">count =</span> <span class="fu">n</span>(),</span>
<span id="cb139-5"><a href="twowayANOVA.html#cb139-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(time, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb139-6"><a href="twowayANOVA.html#cb139-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(time, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb139-7"><a href="twowayANOVA.html#cb139-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">median</span>(time, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb139-8"><a href="twowayANOVA.html#cb139-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;florist&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="twowayANOVA.html#cb141-1" aria-hidden="true" tabindex="-1"></a>sum_df</span></code></pre></div>
<pre><code>## # A tibble: 4 × 6
## # Groups:   florist [2]
##   florist customer count  mean    sd median
##   &lt;fct&gt;   &lt;fct&gt;    &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1 0       0            6   9.9 1.73    10.5
## 2 0       1            6  11.0 2.03    11.4
## 3 1       0            6  10.6 1.06    10.4
## 4 1       1            6  13.8 0.965   13.4</code></pre>
<p>This table suggest that applying fertilizer at both the florist and the costumer simultaniously has a large possitive effect on the lifespan of the roses, i.e. it suggests there is an interaction effect.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="twowayANOVA.html#cb143-1" aria-hidden="true" tabindex="-1"></a>sum_customer <span class="sc">%&gt;%</span></span>
<span id="cb143-2"><a href="twowayANOVA.html#cb143-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> customer, <span class="at">y =</span> mean_time, <span class="at">fill =</span> customer)) <span class="sc">+</span> </span>
<span id="cb143-3"><a href="twowayANOVA.html#cb143-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">&quot;identity&quot;</span>, </span>
<span id="cb143-4"><a href="twowayANOVA.html#cb143-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">position=</span><span class="fu">position_dodge</span>(), <span class="at">width =</span> .<span class="dv">65</span>) <span class="sc">+</span></span>
<span id="cb143-5"><a href="twowayANOVA.html#cb143-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean_time<span class="sc">-</span> sd_time, <span class="at">ymax =</span> mean_time<span class="sc">+</span> sd_time), <span class="at">width=</span>.<span class="dv">2</span>,</span>
<span id="cb143-6"><a href="twowayANOVA.html#cb143-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">position=</span><span class="fu">position_dodge</span>(.<span class="dv">9</span>)) <span class="sc">+</span> </span>
<span id="cb143-7"><a href="twowayANOVA.html#cb143-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">&quot;Barplot of sample means with error bars (+/- SD) for `customer`&quot;</span>,</span>
<span id="cb143-8"><a href="twowayANOVA.html#cb143-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">&quot;Fertilizer added at customer&quot;</span>, <span class="at">y =</span> <span class="st">&quot;time&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;customer&quot;</span>) <span class="sc">+</span></span>
<span id="cb143-9"><a href="twowayANOVA.html#cb143-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="st">&quot;0&quot;</span>,<span class="st">&quot;1&quot;</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>)) <span class="sc">+</span></span>
<span id="cb143-10"><a href="twowayANOVA.html#cb143-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="st">&quot;0&quot;</span>,<span class="st">&quot;1&quot;</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/x9-1.png" width="672" /></p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="twowayANOVA.html#cb144-1" aria-hidden="true" tabindex="-1"></a>sum_florist <span class="sc">%&gt;%</span> </span>
<span id="cb144-2"><a href="twowayANOVA.html#cb144-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> florist, <span class="at">y =</span> mean_time, <span class="at">fill =</span> florist)) <span class="sc">+</span> </span>
<span id="cb144-3"><a href="twowayANOVA.html#cb144-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">&quot;identity&quot;</span>, </span>
<span id="cb144-4"><a href="twowayANOVA.html#cb144-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">position=</span><span class="fu">position_dodge</span>(), <span class="at">width =</span> .<span class="dv">65</span>) <span class="sc">+</span></span>
<span id="cb144-5"><a href="twowayANOVA.html#cb144-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean_time<span class="sc">-</span> sd_time, <span class="at">ymax =</span> mean_time <span class="sc">+</span> sd_time), <span class="at">width=</span>.<span class="dv">2</span>,</span>
<span id="cb144-6"><a href="twowayANOVA.html#cb144-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">position=</span><span class="fu">position_dodge</span>(.<span class="dv">9</span>)) <span class="sc">+</span> </span>
<span id="cb144-7"><a href="twowayANOVA.html#cb144-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">&quot;Barplot of sample means with error bars (+/- SD) for `florist`&quot;</span>, <span class="at">x=</span><span class="st">&quot;Fertilizer added at florist&quot;</span>, <span class="at">y =</span> <span class="st">&quot;time&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;florist&quot;</span>) <span class="sc">+</span></span>
<span id="cb144-8"><a href="twowayANOVA.html#cb144-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="st">&quot;0&quot;</span>,<span class="st">&quot;1&quot;</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>)) <span class="sc">+</span></span>
<span id="cb144-9"><a href="twowayANOVA.html#cb144-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="st">&quot;0&quot;</span>,<span class="st">&quot;1&quot;</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/x10-1.png" width="672" /></p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="twowayANOVA.html#cb145-1" aria-hidden="true" tabindex="-1"></a>sum_df <span class="sc">%&gt;%</span> </span>
<span id="cb145-2"><a href="twowayANOVA.html#cb145-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> florist, <span class="at">y =</span> mean, <span class="at">fill =</span> customer)) <span class="sc">+</span> </span>
<span id="cb145-3"><a href="twowayANOVA.html#cb145-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">position =</span> <span class="st">&quot;dodge&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb145-4"><a href="twowayANOVA.html#cb145-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(</span>
<span id="cb145-5"><a href="twowayANOVA.html#cb145-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">ymin=</span>mean<span class="sc">-</span>sd,</span>
<span id="cb145-6"><a href="twowayANOVA.html#cb145-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">ymax=</span>mean<span class="sc">+</span>sd),</span>
<span id="cb145-7"><a href="twowayANOVA.html#cb145-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="fl">0.9</span>),</span>
<span id="cb145-8"><a href="twowayANOVA.html#cb145-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb145-9"><a href="twowayANOVA.html#cb145-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb145-10"><a href="twowayANOVA.html#cb145-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title=</span><span class="st">&quot;Barplot of sample means with error bars (+/- SD) for `florist`&quot;</span>, </span>
<span id="cb145-11"><a href="twowayANOVA.html#cb145-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x=</span><span class="st">&quot;Fertilizer added at florist&quot;</span>, <span class="at">y =</span> <span class="st">&quot;time&quot;</span>)<span class="sc">+</span></span>
<span id="cb145-12"><a href="twowayANOVA.html#cb145-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(</span>
<span id="cb145-13"><a href="twowayANOVA.html#cb145-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks=</span><span class="fu">c</span>(<span class="st">&quot;0&quot;</span>,<span class="st">&quot;1&quot;</span>),</span>
<span id="cb145-14"><a href="twowayANOVA.html#cb145-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>)) <span class="sc">+</span></span>
<span id="cb145-15"><a href="twowayANOVA.html#cb145-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(</span>
<span id="cb145-16"><a href="twowayANOVA.html#cb145-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks=</span><span class="fu">c</span>(<span class="st">&quot;0&quot;</span>,<span class="st">&quot;1&quot;</span>),</span>
<span id="cb145-17"><a href="twowayANOVA.html#cb145-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/x11-1.png" width="672" /></p>
<p>A boxplot can be good to see if there is an interaction effect (If applying fertilizer only have an effect if it is done both places)</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="twowayANOVA.html#cb146-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb146-2"><a href="twowayANOVA.html#cb146-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb146-3"><a href="twowayANOVA.html#cb146-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x=</span>florist, </span>
<span id="cb146-4"><a href="twowayANOVA.html#cb146-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">y=</span>time, </span>
<span id="cb146-5"><a href="twowayANOVA.html#cb146-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">color =</span> customer)) <span class="sc">+</span> </span>
<span id="cb146-6"><a href="twowayANOVA.html#cb146-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(</span>
<span id="cb146-7"><a href="twowayANOVA.html#cb146-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">outlier.colour=</span><span class="st">&quot;red&quot;</span>, </span>
<span id="cb146-8"><a href="twowayANOVA.html#cb146-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">outlier.shape=</span><span class="dv">8</span>,</span>
<span id="cb146-9"><a href="twowayANOVA.html#cb146-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">outlier.size=</span><span class="dv">4</span>)<span class="sc">+</span></span>
<span id="cb146-10"><a href="twowayANOVA.html#cb146-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(</span>
<span id="cb146-11"><a href="twowayANOVA.html#cb146-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks=</span><span class="fu">c</span>(<span class="st">&quot;0&quot;</span>,<span class="st">&quot;1&quot;</span>),</span>
<span id="cb146-12"><a href="twowayANOVA.html#cb146-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>)) <span class="sc">+</span></span>
<span id="cb146-13"><a href="twowayANOVA.html#cb146-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_discrete</span>(</span>
<span id="cb146-14"><a href="twowayANOVA.html#cb146-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks=</span><span class="fu">c</span>(<span class="st">&quot;0&quot;</span>,<span class="st">&quot;1&quot;</span>),</span>
<span id="cb146-15"><a href="twowayANOVA.html#cb146-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/x12-1.png" width="672" /></p>
<p>Here we can see that applying the fertilizer at the costumer and not the dealer, has a small positive effect, but applying both at the dealer and the costumers seems to have a large positive effect.</p>
</div>
<div id="fitting-model-2" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Fitting model<a href="twowayANOVA.html#fitting-model-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="twowayANOVA.html#cb147-1" aria-hidden="true" tabindex="-1"></a>m1_interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(time <span class="sc">~</span> florist<span class="sc">*</span>customer, <span class="at">data =</span> df)</span></code></pre></div>
<p>Doing a drop1 test on our models we can see which terms in the model are considered significant, and should be kept in the model</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="twowayANOVA.html#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(m1_interaction, <span class="at">test =</span> <span class="st">&quot;F&quot;</span>)</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## time ~ florist * customer
##                  Df Sum of Sq    RSS    AIC F value  Pr(&gt;F)  
## &lt;none&gt;                        45.757 23.487                  
## florist:customer  1    6.8267 52.583 24.824  2.9839 0.09951 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Here we see that florist and customer are significant terms while the interaction between the two is not significant.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="twowayANOVA.html#cb150-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(time <span class="sc">~</span> florist <span class="sc">+</span> customer, <span class="at">data =</span> df)</span></code></pre></div>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="twowayANOVA.html#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(m1, <span class="at">test =</span> <span class="st">&quot;F&quot;</span>)</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## time ~ florist + customer
##          Df Sum of Sq    RSS    AIC F value   Pr(&gt;F)   
## &lt;none&gt;                52.583 24.824                    
## florist   1    19.440 72.023 30.374  7.7637 0.011063 * 
## customer  1    27.735 80.318 32.991 11.0764 0.003193 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="validating-the-model-1" class="section level2 hasAnchor" number="7.5">
<h2><span class="header-section-number">7.5</span> Validating the model<a href="twowayANOVA.html#validating-the-model-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="why-do-i-need-to-valide-the-model-1" class="section level3 hasAnchor" number="7.5.1">
<h3><span class="header-section-number">7.5.1</span> Why do I need to valide the model?<a href="twowayANOVA.html#why-do-i-need-to-valide-the-model-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The two-way ANOVA can only be used given these three assumption:</p>
<ul>
<li>Independence of observations: Observations within each group are independent</li>
<li>Homogeneity of variance: The variation around the mean for each group being compared should be similar among all groups</li>
<li>Normal-distributed dependent variable: The depended variable should be normally distributed</li>
</ul>
<p>All that we extract from the two-way ANOVA model about uncertainty of estimates (later also tests) is only valid if the model assumptions are valid.</p>
</div>
<div id="how-do-i-validate-the-model-assumptions-1" class="section level3 hasAnchor" number="7.5.2">
<h3><span class="header-section-number">7.5.2</span> How do I validate the model assumptions?<a href="twowayANOVA.html#how-do-i-validate-the-model-assumptions-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <code>plot()</code> function makes it easy to check the latter two assumptions about homoscedasticity and normal-distributed dependent variable. To check if the variation around the mean for each group being compared is similar among all groups we can do the following on the fitted model (here we use the model with an interaction effect):</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="twowayANOVA.html#cb153-1" aria-hidden="true" tabindex="-1"></a><span class="co">#homogeneity of variance assumption</span></span>
<span id="cb153-2"><a href="twowayANOVA.html#cb153-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m1, <span class="dv">1</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/x17-1.png" width="672" /></p>
<p>Here the assumption is fulfilled if the red line is horizontal. In this example it is almost perfectly horizontal and we would say that the assumption is fulfilled.</p>
<p>To check if the dependent variable is normally distributed we can make a qq-plot of the residuals:</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="twowayANOVA.html#cb154-1" aria-hidden="true" tabindex="-1"></a><span class="co">#normality assumpttion</span></span>
<span id="cb154-2"><a href="twowayANOVA.html#cb154-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m1, <span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/x18-1.png" width="672" /></p>
<p>For the assumption to be fulfilled the dots need to follow the dotted line.</p>
</div>
</div>
<div id="hypothesis-test-2" class="section level2 hasAnchor" number="7.6">
<h2><span class="header-section-number">7.6</span> Hypothesis test<a href="twowayANOVA.html#hypothesis-test-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To do the two-way-ANOVA we need our fitted model and then do the test using <code>joint_tests()</code>.</p>
<p>First we will do a two-way anova on the linear model with an interaction effect <code>time ~ florist + customer + florist:customer</code>, as our data exploration suggests that there may be one. The null hypothesis for this model are the same two as before plus an additional one: Applying fertilizer at the shop has no effect on the effect of applying fertilizer at the costumer.</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="twowayANOVA.html#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="fu">joint_tests</span>(m1_interaction)</span></code></pre></div>
<pre><code>##  model term       df1 df2 F.ratio p.value
##  florist            1  20   8.497  0.0086
##  customer           1  20  12.123  0.0024
##  florist:customer   1  20   2.984  0.0995</code></pre>
<p>From the summary we get a p-value of 0.0995 on the interaction effect, which means we cannot reject the null hypothesis based on our data.</p>
<p>Now we will do a two-way anova on the linear model <code>time ~ florist + customer</code>. The null hypothesis for this model are: There is no significant difference on the lifespan of the roses between applying fertilizer and not applying fertilizer at the florist, and there is no significant difference on the lifespan of the roses between applying fertilizer and not applying fertilizer at costumer.</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="twowayANOVA.html#cb157-1" aria-hidden="true" tabindex="-1"></a><span class="fu">joint_tests</span>(m1)</span></code></pre></div>
<pre><code>##  model term df1 df2 F.ratio p.value
##  florist      1  21   7.764  0.0111
##  customer     1  21  11.076  0.0032</code></pre>
<p>From the summary we can see the p-value for applying fertilizer at the shop is 0.011, which means based on this test we can reject the null-hypothesis, i.e. this test suggest that there is a significant difference on whether you apply or dont apply fertilizer at the florist.
The same conclusion can be drawn from the second p-value as it is 0.003.</p>
</div>
<div id="extracting-estimates-with-emmeans-1" class="section level2 hasAnchor" number="7.7">
<h2><span class="header-section-number">7.7</span> Extracting estimates with <code>emmeans()</code><a href="twowayANOVA.html#extracting-estimates-with-emmeans-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Here we use the function <code>emmeans()</code> to calculate the estimated marginal means for all possible values of the factor variables:</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="twowayANOVA.html#cb159-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(m1_interaction,  <span class="sc">~</span> florist<span class="sc">*</span>customer, <span class="at">test =</span> <span class="st">&quot;F&quot;</span>)</span>
<span id="cb159-2"><a href="twowayANOVA.html#cb159-2" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##  florist customer emmean    SE df lower.CL upper.CL
##  0       0           9.9 0.617 20     8.61     11.2
##  1       0          10.6 0.617 20     9.35     11.9
##  0       1          11.0 0.617 20     9.70     12.3
##  1       1          13.8 0.617 20    12.56     15.1
## 
## Confidence level used: 0.95</code></pre>
<p>Now we want to compare the estimated means between values of the factor variables. This is called the constrasts:</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="twowayANOVA.html#cb161-1" aria-hidden="true" tabindex="-1"></a>m <span class="sc">%&gt;%</span> <span class="fu">pairs</span>(<span class="at">simple =</span> <span class="st">&quot;florist&quot;</span>)</span></code></pre></div>
<pre><code>## customer = 0:
##  contrast            estimate    SE df t.ratio p.value
##  florist0 - florist1   -0.733 0.873 20  -0.840  0.4110
## 
## customer = 1:
##  contrast            estimate    SE df t.ratio p.value
##  florist0 - florist1   -2.867 0.873 20  -3.283  0.0037</code></pre>
<p>Here we see that the mean for Florist = 0 is not significantly different from the mean for Florist = 1 when Customer = 0, but they are significantly different when customer is 1.</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="twowayANOVA.html#cb163-1" aria-hidden="true" tabindex="-1"></a>m <span class="sc">%&gt;%</span> <span class="fu">pairs</span>(<span class="at">simple =</span> <span class="st">&quot;customer&quot;</span>)</span></code></pre></div>
<pre><code>## florist = 0:
##  contrast              estimate    SE df t.ratio p.value
##  customer0 - customer1    -1.08 0.873 20  -1.241  0.2291
## 
## florist = 1:
##  contrast              estimate    SE df t.ratio p.value
##  customer0 - customer1    -3.22 0.873 20  -3.683  0.0015</code></pre>
<p>Here we see that the mean for Customer = 0 is not significantly different from the mean for Customer = 1 when Florist = 0, but they are significantly different when Florist is 1.</p>
<p>In can be of interest to take the contrast of the contrasts, to see if the effect of <code>florist</code> is different depending on <code>customer</code> (i.e. the interaction effect).</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="twowayANOVA.html#cb165-1" aria-hidden="true" tabindex="-1"></a>m <span class="sc">%&gt;%</span> </span>
<span id="cb165-2"><a href="twowayANOVA.html#cb165-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>(<span class="at">simple =</span> <span class="st">&quot;florist&quot;</span>) <span class="sc">%&gt;%</span> <span class="do">## Order of florist and customer does not matter</span></span>
<span id="cb165-3"><a href="twowayANOVA.html#cb165-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>(<span class="at">simple =</span> <span class="st">&quot;customer&quot;</span>,<span class="at">by =</span> <span class="cn">NULL</span>)</span></code></pre></div>
<pre><code>## contrast = florist0 - florist1:
##  contrast1             estimate   SE df t.ratio p.value
##  customer0 - customer1     2.13 1.23 20   1.727  0.0995</code></pre>
<p>Here we see that that the interaction effect is not significant.</p>
</div>
<div id="writing-articlereport" class="section level2 hasAnchor" number="7.8">
<h2><span class="header-section-number">7.8</span> Writing article/report<a href="twowayANOVA.html#writing-articlereport" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="how-to-write-method-section" class="section level3 hasAnchor" number="7.8.1">
<h3><span class="header-section-number">7.8.1</span> How to write method section<a href="twowayANOVA.html#how-to-write-method-section" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In a method section one should clearly state the methods used to produce the results presented in the paper, such that anyone reading the paper can reproduce the result given the same data. Here is an example:</p>
<p>To test whether applying fertilizer to the roses at the florist or the customer, has an effect on their lifespan, we have choosen to do a two-way-ANOVA test. This will also be done on their interaction effect to see if applying fertilizer both places has a bigger effect.</p>
</div>
<div id="how-to-write-results-section" class="section level3 hasAnchor" number="7.8.2">
<h3><span class="header-section-number">7.8.2</span> How to write results section<a href="twowayANOVA.html#how-to-write-results-section" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Doing the two-way-ANOVA test we find that both <code>florist</code> and <code>customer</code> are significant, while their interaction is not, meaning, based on the test, that there is a significant difference on whether you apply or don’t apply fertilizer at the florist or at the customer, and no significant difference between applying it at both at the same time.</p>
</div>
</div>
<div id="miscellaneous-1" class="section level2 hasAnchor" number="7.9">
<h2><span class="header-section-number">7.9</span> Miscellaneous<a href="twowayANOVA.html#miscellaneous-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="why-to-not-use-anova-tables" class="section level3 hasAnchor" number="7.9.1">
<h3><span class="header-section-number">7.9.1</span> Why to not use ANOVA tables<a href="twowayANOVA.html#why-to-not-use-anova-tables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The classical ANOVA-table only works if the dataset is balanced (there are equal number of observations of each label within a factor). In our case this is true and we can see that <code>anova()</code> and <code>joint_test()</code> outputs the same p values (except for some rounding):</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="twowayANOVA.html#cb167-1" aria-hidden="true" tabindex="-1"></a><span class="fu">joint_tests</span>(m1_interaction)</span></code></pre></div>
<pre><code>##  model term       df1 df2 F.ratio p.value
##  florist            1  20   8.497  0.0086
##  customer           1  20  12.123  0.0024
##  florist:customer   1  20   2.984  0.0995</code></pre>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="twowayANOVA.html#cb169-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1_interaction)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: time
##                  Df Sum Sq Mean Sq F value   Pr(&gt;F)   
## florist           1 19.440 19.4400  8.4971 0.008563 **
## customer          1 27.735 27.7350 12.1228 0.002352 **
## florist:customer  1  6.827  6.8267  2.9839 0.099509 . 
## Residuals        20 45.757  2.2878                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Now i remove the 3 first observations in our dataset and we can see that the two methods output different p-values</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="twowayANOVA.html#cb171-1" aria-hidden="true" tabindex="-1"></a>m_test <span class="ot">&lt;-</span> <span class="fu">lm</span>(time <span class="sc">~</span> florist<span class="sc">*</span>customer, <span class="at">data =</span> df[<span class="sc">-</span><span class="dv">1</span><span class="sc">:-</span><span class="dv">3</span>,])</span>
<span id="cb171-2"><a href="twowayANOVA.html#cb171-2" aria-hidden="true" tabindex="-1"></a><span class="fu">joint_tests</span>(m_test)</span></code></pre></div>
<pre><code>##  model term       df1 df2 F.ratio p.value
##  florist            1  17   7.086  0.0164
##  customer           1  17   9.910  0.0059
##  florist:customer   1  17   1.741  0.2045</code></pre>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="twowayANOVA.html#cb173-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m_test)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: time
##                  Df Sum Sq Mean Sq F value   Pr(&gt;F)   
## florist           1 14.814 14.8143  5.9533 0.025939 * 
## customer          1 30.176 30.1761 12.1265 0.002851 **
## florist:customer  1  4.332  4.3320  1.7409 0.204526   
## Residuals        17 42.303  2.4884                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Now the order in which our variables are written in the model also changes the results in the <code>anova()</code> table while it is the same for <code>joint_test()</code></p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="twowayANOVA.html#cb175-1" aria-hidden="true" tabindex="-1"></a>m_test2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(time <span class="sc">~</span> customer<span class="sc">*</span>florist, <span class="at">data =</span> df[<span class="sc">-</span><span class="dv">1</span><span class="sc">:-</span><span class="dv">3</span>,])</span>
<span id="cb175-2"><a href="twowayANOVA.html#cb175-2" aria-hidden="true" tabindex="-1"></a><span class="fu">joint_tests</span>(m_test2)</span></code></pre></div>
<pre><code>##  model term       df1 df2 F.ratio p.value
##  customer           1  17   9.910  0.0059
##  florist            1  17   7.086  0.0164
##  customer:florist   1  17   1.741  0.2045</code></pre>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="twowayANOVA.html#cb177-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m_test2)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: time
##                  Df Sum Sq Mean Sq F value   Pr(&gt;F)   
## customer          1 22.800 22.8002  9.1625 0.007605 **
## florist           1 22.190 22.1902  8.9174 0.008295 **
## customer:florist  1  4.332  4.3320  1.7409 0.204526   
## Residuals        17 42.303  2.4884                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="mixedmodels.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/HjalteSoeberg/DataLab_StudCons/edit/main/twowayANOVA.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/HjalteSoeberg/DataLab_StudCons/blob/main/twowayANOVA.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
